/**
 * API CRUD scenario -- exercises the core investigation and remediation
 * create / list / detail endpoints under sustained load.
 *
 * Usage:
 *   k6 run tests/load/scenarios/api-crud.js
 *   k6 run tests/load/scenarios/api-crud.js -e API_URL=http://staging:8000/api/v1
 *
 * Stage profiles can be selected via the PROFILE env var:
 *   k6 run tests/load/scenarios/api-crud.js -e PROFILE=stress
 */

import { group, sleep } from 'k6';
import {
  BASE_URL,
  STAGES,
  THRESHOLDS,
  THRESHOLDS_RELAXED,
  TEST_EMAIL,
  TEST_PASSWORD,
} from '../config.js';
import { login, authGet, authPost, randomInt, randomChoice } from '../helpers.js';

const profile = __ENV.PROFILE || 'load';

export const options = {
  stages: STAGES[profile] || STAGES.load,
  thresholds: {
    ...THRESHOLDS,
    // Write endpoints return 202 (async) and may be slower.
    'http_req_duration{name:create_investigation}': ['p(95)<500'],
    'http_req_duration{name:create_remediation}': ['p(95)<500'],
  },
};

// --- Setup -----------------------------------------------------------------

export function setup() {
  const token = login(TEST_EMAIL, TEST_PASSWORD);
  if (!token) {
    throw new Error('Setup failed: could not authenticate.');
  }
  return { token };
}

// --- VU iteration ----------------------------------------------------------

export default function (data) {
  const token = data.token;

  // ── Investigations ───────────────────────────────────────────────────
  group('investigations', () => {
    // List investigations with random pagination
    const offset = randomInt(0, 5) * 10;
    const listRes = authGet(
      `/investigations?limit=10&offset=${offset}`,
      token,
      200,
      'list_investigations',
    );

    // Attempt to fetch a detail if we got results
    try {
      const body = JSON.parse(listRes.body);
      const items = body.investigations || [];
      if (items.length > 0) {
        const item = randomChoice(items);
        const id = item.investigation_id || item.id;
        if (id) {
          authGet(`/investigations/${id}`, token, 200, 'get_investigation');
        }
      }
    } catch (_) {
      // If parsing fails, skip detail fetch -- not a test failure.
    }

    // Create a new investigation (async -- returns 202)
    if (randomInt(0, 10) < 3) {
      // ~30% of iterations create a new one to avoid overwhelming the queue
      const payload = {
        alert_id: `load-alert-${Date.now()}-${randomInt(1000, 9999)}`,
        alert_name: 'LoadTest: High CPU',
        severity: randomChoice(['warning', 'critical', 'info']),
        source: 'k6-load-test',
        description: 'Synthetic alert generated by k6 load test',
        labels: { team: 'sre', env: 'load-test' },
      };
      authPost('/investigations', payload, token, 202, 'create_investigation');
    }
  });

  // ── Remediations ─────────────────────────────────────────────────────
  group('remediations', () => {
    const offset = randomInt(0, 5) * 10;
    const listRes = authGet(
      `/remediations?limit=10&offset=${offset}`,
      token,
      200,
      'list_remediations',
    );

    try {
      const body = JSON.parse(listRes.body);
      const items = body.remediations || [];
      if (items.length > 0) {
        const item = randomChoice(items);
        const id = item.remediation_id || item.id;
        if (id) {
          authGet(`/remediations/${id}`, token, 200, 'get_remediation');
        }
      }
    } catch (_) {
      // skip
    }

    // Create a new remediation (~20% of iterations)
    if (randomInt(0, 10) < 2) {
      const payload = {
        action_type: randomChoice(['restart_service', 'scale_up', 'rollback_deploy']),
        target_resource: `svc-${randomChoice(['api', 'worker', 'cache', 'db'])}-${randomInt(1, 5)}`,
        environment: randomChoice(['production', 'staging']),
        risk_level: randomChoice(['low', 'medium', 'high']),
        description: 'Synthetic remediation from k6 load test',
        parameters: { replicas: randomInt(2, 8) },
      };
      authPost('/remediations', payload, token, 202, 'create_remediation');
    }
  });

  sleep(randomInt(1, 3));
}
