name: "Setup Python (cached)"
description: "Set up Python 3.12, restore pip cache, and install dev dependencies"

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.12"
  install-args:
    description: "Extra pip install arguments (e.g. '.[dev]')"
    required: false
    default: ".[dev]"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          pip-${{ runner.os }}-${{ inputs.python-version }}-

    - run: pip install -e "${{ inputs.install-args }}"
      shell: bash
